### ISSUE TITLE
ERROR:floss:Vivisect failed to load the input file: No module named entrypoints

### ISSUE THREAD

**Issue by DigiAngel** [vivisect/vivisect#278]
After updating I'm seeing the above with floss.  Thank you!

**Comment by rakuy0** [comment]
Hmmm. We do have a module called `entrypoints`  under `vivisect/analysis/generic/` that was added back in late October. So relatively new.

To try and diagnose what's going on:
* Does it happen for just one binary, or every binary you analyze?
* Can you confirm the file vivisect/analysis/generic/entrypoints.py exists?
* What's the git hash of your vivisect checkout (from something like `git rev-parse HEAD`)? 
* What does your PYTHONPATH env var look like?
* Since I'm not super familiar with how floss does its thing, does it do anything to fetch and install vivisect?
* Do you have a full backtrace of the exception?

**Comment by DigiAngel** [comment]
~~~
Does it happen for just one binary, or every binary you analyze?
~~~
On every binary..just tested.
~~~
Can you confirm the file vivisect/analysis/generic/entrypoints.py exists?
~~~
Yes 272 Nov 11 05:42 entrypoints.py
~~~
What's the git hash of your vivisect checkout (from something like git rev-parse HEAD)?
~~~
Hash is \26b3de4f19b7c9fd19241cb4b381f2db5cd3134e\
~~~
What does your PYTHONPATH env var look like?
~~~
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/local/lib/python2.7/dist-packages/capstone-5.0.0-py2.7.egg
/usr/local/lib/python2.7/dist-packages/unicorn-1.0.2-py2.7.egg
/usr/local/lib/python2.7/dist-packages/mLib-1.2.5-py2.7.egg
/usr/lib/python2.7/dist-packages
~~~
Since I'm not super familiar with how floss does its thing, does it do anything to fetch and install vivisect?
~~~
Negative...last updated was 2017 https://github.com/fireeye/flare-floss
~~~
Do you have a full backtrace of the exception?
~~~
I do not...I'm a little fuzzy on how to get those....thank you!

**Comment by DigiAngel** [comment]
I'm using the latest precompiled floss btw.

**Comment by rakuy0** [comment]
Weird. You're on the latest master and the error is at least consistent. And when I grab the latest floss (Spring Snake, version 1.5.0), it runs fine. Even if I checkout a super old version of vivisect, remove vivisect from my PYTHONPATH, or run it on a VM that vivisect has never touched, it works.

What's even stranger is they're bundling vivisect into their frozen python binary, and if it's from 2017, it shouldn't even have references to the entrypoints analysis module.

So two things from that:
* If you're on linux, is the sha256 of your floss executable 056907e6643ab01e2d599bfdb4bece246475f40909790308a119a2b59e56c216 ?
* In trying to reproduce this on my end, how are you running floss? Because so far my attempts have failed to reproduce that exception (on linux only so far).

**Comment by williballenthin** [comment]
i recently synced our branch of vivisect (at this point, it probably contains only packaging fixes), which pulled in the new entrypoints analyzer. we use pyinstaller to package vivisect into our standalone exe. however, because viv dynamically builds the analyzer import, pyinstaller doesn't package it without extra directive. so, the nightly builds of floss are failing, because they don't get packaged with the latest analyzer files.

we have to update our spec file here: https://github.com/fireeye/flare-floss/blob/master/floss.spec#L18

incidentally, it would be awesome to remove the dynamic imports from viv, at least making them conditional imports

**Comment by williballenthin** [comment]
(this is not a bug with viv, but a bug with floss)

**Comment by DigiAngel** [comment]
Thank you @williballenthin ...I'll close this ticket out.

**Comment by rakuy0** [comment]
Yea. It would be nice to remove the dynamic imports. Bigger fish to fry for right now though.

**Comment by atlas0fd00m** [comment]
> i recently synced our branch of vivisect (at this point, it probably contains only packaging fixes), which pulled in the new entrypoints analyzer. we use pyinstaller to package vivisect into our standalone exe. however, because viv dynamically builds the analyzer import, pyinstaller doesn't package it without extra directive. so, the nightly builds of floss are failing, because they don't get packaged with the latest analyzer files.
> 
> we have to update our spec file here: https://github.com/fireeye/flare-floss/blob/master/floss.spec#L18
> 
> incidentally, it would be awesome to remove the dynamic imports from viv, at least making them conditional imports

@williballenthin, my apologies for messing up your analysis process!  we moved the entrypoints analysis into it's own module so we have control over what happens before processing initial codeflow analysis.  this helps make things like ELF PLT processing easier to control and anticipate.

can you be more specific in your request about dynamic imports?  what would you like to make conditional, and how would you suggest?

**Comment by williballenthin** [comment]
@atlas0fd00m no worries about the changes! makes plenty of sense to split it out. managing the packaging of the downstream tool is our business ;-)

regarding the imports: ideally, yes, i'd like to see them converted over to conditional imports, rather than dynamic imports. for example:

yes:
```
if today == 'tuesday':
    import vivisect.analysis.generic.entrypoints
```

no:
```
if today == 'tuesday':
    __import__('vivisect.analysis.generic.' + 'entrypoints')
```

reasoning: in the former, code analysis tools, including pyinstaller, can compute the set off all dependencies that could ever be imported. in the latter, the code analysis tool has to do some sort of emulation or symbolic analysis to figure out the import targets, which is probably not really feasible.

i understand that its convenient to provide shortcuts like `addAnalysisModule("pe")` that dynamically creates the import path, especially since this means you could just drop extensions into analyzer directory. however, i'm not aware that vivisect users actually *do* this today. so, can we change the implementation of `addAnalysisModule()` to look more like:

```
if modname == "pe":
    import vivisect.analysis.pe
    return vivisect.analysis.pe
elseif modname == "macho":
    ...
```

**Comment by atlas0fd00m** [comment]
thank you for the clarification, @williballenthin !  that makes a lot more sense to me.
unfortunately, this is at the very core of Vivisect's Extensions and Scripting capabilities, among other things (like Import API's, and as you've alluded to, the various Analysis Modules).

for scripting and extensions, i don't know of a better (or even different) way that would suit your request.
and unfortunately, i'm trying to work more toward extensibility for things like file parsers, analysis modules, and disassemblers.  is there some method which would allow us to make these subsystems more flexible and still provide what you need?

**Comment by williballenthin** [comment]
if you expect to use the extensibility features of dynamic importing more, then no requests from me. we'll continue to update our pyinstaller spec as we find analyzers getting added to viv. its not too much work and pretty simple - just an occasional hiccup like here.

thanks!
