### ISSUE TITLE
i386: incorrect disassembly for `6A FF`

### ISSUE THREAD

**Issue by williballenthin** [vivisect/vivisect#296]
for intel x86/64, `6A FF` should be decoded to `push 0xFFFFFFFF[FFFFFFFF]`; however, its currently decoded to `push 0xFF`

![image](https://user-images.githubusercontent.com/156560/88416571-ac26b980-cd9d-11ea-80cf-f45a54236284.png)

originally identified here: https://github.com/fireeye/capa-rules/issues/49#issuecomment-663288748

i can provide a test case once i get a handle on this bug. i figure the relevant line is here: https://github.com/vivisect/vivisect/blob/master/envi/archs/i386/opcode86.py#L121

**Comment by williballenthin** [comment]
i *think* we're dealing with this case:
![image](https://user-images.githubusercontent.com/156560/88425010-e008db80-cdab-11ea-8bd0-4daa0f728649.png)
https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf

**Comment by rakuy0** [comment]
Ah. Yea. That's my copy of the manual says. The instruction declares that operand as a 8 bit value, but the intel manual sneaks in: `If the source operand is an immediate of size less than the operand size, a sign-extended value is pushed on the stack.`

So that line needs an OP_SIGNED and the decoder needs some other tweaks to better handle operand sizes for that. I should have something up by early next week to deal with this.

**Comment by williballenthin** [comment]
awesome, thanks!

**Comment by williballenthin** [comment]
thank you!
