### ISSUE TITLE
cobra: use `six` for py2+py3 compatibility

### ISSUE THREAD

**Issue by williballenthin** [vivisect/vivisect#345]
im looking to use cobra from py3. currently it doesn't work due to py2 imports having moved. would you accept a PR that enables cobra to work on both py2 and py3 via the [six](https://six.readthedocs.io/) compatibility library?

no worries if not, i can keep my fork local, too.

![image](https://user-images.githubusercontent.com/156560/105750656-41983700-5f02-11eb-971b-7a07186f9b8f.png)

**Comment by williballenthin** [comment]
there were some further changes i had to make to cobra to get it working on py3, but it does work (even against a py2 remote application). still happy to contribute these, though i don't to become known as a cobra maintainer ;-)

**Comment by rakuy0** [comment]
So before I say yes or not, I'd need to checking if my py3 branch interoperates with a py2 cobra instance. If it does interoperate as we would hope, I'd kinda just like to wait for that branch to land since it's really close. If it doesn't, I'm a lot more curious about what you did.

As for you being a cobra maintainer. Well...you touched it last :laughing:

**Comment by williballenthin** [comment]
ok, lets close this out and re-open if necessary in the future.
