### ISSUE TITLE
default config not created in python3

### ISSUE THREAD

**Issue by sprout42** [vivisect/vivisect#350]
I'm trying out the latest python 3 changes and found if I don't have a config file already, a new one doesn't get created even when I add the `--autosave` CLI option.  If I add
```
if self.autosave:
    self.saveConfigFile()
```
to the end of the `envi.config.EnviConfig` class constructor it will save the default values into a config for me, but I'm not sure if this is what the autosave command option is meant to do.

I also had to change the file mode in `EnviConfig.saveConfigFile()` function to be "w" instead of "wb".

```
$ ls ~/.viv
ls: .viv: No such file or directory
$ python -m vivisect.vivbin -a
$ ls ~/.viv/
viv.json
```

Here is a diff of the changes I made:
```
diff --git a/envi/config.py b/envi/config.py
index 886861c..dc74000 100644
--- a/envi/config.py
+++ b/envi/config.py
@@ -67,6 +67,9 @@ class EnviConfig:
         if docs is not None:
             self.setDocsPrimitive(docs)
 
+        if self.autosave:
+            self.saveConfigFile()
+
     def getOptionDoc(self, optname):
         '''
         Retrieve docs about the given option if present.
@@ -219,7 +222,7 @@ class EnviConfig:
             filename = self.filename
 
         cfgdict = self.getConfigPrimitive()
-        with open(filename, 'wb') as fd:
+        with open(filename, 'w') as fd:
             json.dump(cfgdict, fd, indent=2)
 
     def loadConfigFile(self, filename=None):
```

**Comment by rakuy0** [comment]
So autosave (originally) would only save config options on change. So if nothing deviates from the defaults, nothing should get written (as there's no need as of yet to write the file out). There was an ask a while ago to make it so that the .viv directory wouldn't get automagically generated (PR #310 ). So unless autosave is on and someone has changed a config option, the config file shouldn't get generated unless a save is explicitly requested. But we should expose something to make that a little easier.

As for the `wb` -> `w` stuff, if you just left it as the `wb` version, does it error out? Or does it just produce garbage? In either case, I'm open to switching that up (I can do it or you can throw up a PR for it, just lemme know). I'm more just curious what's happening.

But Overall, the config stuff hasn't been touched in a while. It's kinda become a second class citizen now since we've been focusing so much on getting analysis more correct.

**Comment by sprout42** [comment]
if I don't do the `wb`->`w` change I get this error when trying to save the config:
```
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.8.2/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/user/.pyenv/versions/3.8.2/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/user/.local/src/vivisect/vivisect/vivbin.py", line 150, in <module>
    main()
  File "/Users/user/.local/src/vivisect/vivisect/vivbin.py", line 59, in main
    vw = viv_cli.VivCli(confdir=args.config, autosave=args.autosave)
  File "/Users/user/.local/src/vivisect/vivisect/cli.py", line 53, in __init__
    vivisect.VivWorkspace.__init__(self, **kwargs)
  File "/Users/user/.local/src/vivisect/vivisect/__init__.py", line 97, in __init__
    self.config = e_config.EnviConfig(filename=cfgpath, defaults=defconfig, docs=docconfig, autosave=autosave)
  File "/Users/user/.local/src/vivisect/envi/config.py", line 71, in __init__
    self.saveConfigFile()
  File "/Users/user/.local/src/vivisect/envi/config.py", line 226, in saveConfigFile
    json.dump(cfgdict, fd, indent=2)
  File "/Users/user/.pyenv/versions/3.8.2/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 180, in dump
    fp.write(chunk)
TypeError: a bytes-like object is required, not 'str'
```
I suppose the `EnviConfig.loadConfigFile()` function needs similar changes.

**Comment by sprout42** [comment]
Regarding the autosave functionality - is there a preferred way to get vivisect to generate a default config file?  If I don't have a configuration file then I am not sure what the preferred way to generate one is.  I have a blob file that I was trying to analyze and I couldn't figure out how to change the `baseaddr` to be 0 before running an analysis on it.

I thought that perhaps the autosave option could do it, but as I said in the issue description I wasn't sure if that is correct or not.

**Comment by rakuy0** [comment]
So there's two ways to get a default config. Best way I can think of, is If you're in the UI, drop into the python REPL, and then try and call `vw.config.saveConfigFile()`. 

I'm not quite sure what the best way to go about making that a little easier to use it yet, but I would like to keep it so it doesn't just autogenerate the configson startup, since we've had requests to specifically not do that in the past. But it does need to change.

And I'll wrap your bytes changes into my general bugfix branch that should be up later today. Thanks for that find!

**Comment by sprout42** [comment]
Makes sense, thanks!
