### ISSUE TITLE
Python2 .viv files are not compatible with Python3

### ISSUE THREAD

**Issue by Ana06** [vivisect/vivisect#363]
Calling `loadWorkspace` using an old `.viv` file generated by vivisect 0.2.0 (Python2) with current master (Python3) raises the following error:
```
  File "/path/vivisect/__init__.py", line 262, in loadWorkspace
    mod.loadWorkspace(self, wsname)
  File "/path/vivisect/storage/basicfile.py", line 57, in loadWorkspace
    events = vivEventsFromFile(filename)
  File "/path/vivisect/storage/basicfile.py", line 47, in vivEventsFromFile
    events.extend(pickle.load(f))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x90 in position 2: ordinal not in range(128)
```

I think this is caused by Python3 default encoding being UTF-8, while it is ASCII for Python2. This could be a problem for applications relaying in the compatibility of .viv files. It may be a good idea to continue storing `.viv` files in ASCII or to provide a compatibility option. Otherwise the next release should document this breaking change.

**Comment by rakuy0** [comment]
So...this is a compatibility thing caused by python's pickle module. I can try later to see if encoding='latin1' or something else works, but as a failsafe measure I also plumbed `vivisect/storage/mpfile.py`, as a compatibility option for 2 to 3 (it's msgpack based instead of pickle).

But yes this is on my list of things to document for the release. I just have to devote most of my time this month to contract work, which is why I haven't been able to do any of the last fiddly bits for a release yet.

So until @atlas0fd00m or I can get around to seeing if we can pickle to work across 2/3, can you give the msgpack module a whirl and see if it works for you? You should be able to invoke it from vivbin via `python -m vivisect.vivbin -s vivisect.storage.mpfile`.

**Comment by rakuy0** [comment]
So with the migration scripts and what not, @Ana06 do those help alleviate this?

**Comment by Ana06** [comment]
We decided in the end not to support compatibility between Python2 and Python3 `.viv` files. We have documented it and we raise an `IncompatibleVivVersion`: https://github.com/williballenthin/viv-utils/blob/master/viv_utils/__init__.py#L70  So this can be closed if you want.
