### ISSUE TITLE
New vivisect release

### ISSUE THREAD

**Issue by mr-tz** [vivisect/vivisect#383]
Can you estimate when there's going to be a new release?

capa's currently blocked in multiple places and we're joyfully anticipating your fixes and improvements 😉

**Comment by evandrix** [comment]
on a related note of `capa`/`vivisect`, is there any way (e.g. command-line switch parameter) to disable the creation of the extra ".viv" workspace file?

**Comment by rakuy0** [comment]
@mr-tz - Aye, should be relatively soon. I'm just trying to get two last relatively important bugfix PRs into master before that  (#384 and #385). Everything else is too far in the WIP stage to consider being in the release.

@evandrix - So that's a separate issue, but vivisect doesn't automatically save the workspace to the .viv file after analysis is done, unless you're doing bulk analysis via the vivbin script, (at which point you're accepting that the workspace file will be created). I don't have specifics on how capa uses vivisect, so I would raise this question towards the capa devs.

**Comment by mr-tz** [comment]
Great, thank you!

@evandrix let's discuss the workspace creation in https://github.com/fireeye/capa/issues/507

**Comment by mr-tz** [comment]
Would it be a good time for a new release now with the two PRs merged?

**Comment by rakuy0** [comment]
I ended up taking the weekend off to celebrate easter with my family (I actually forgot it was this last weekend until someone told me :laughing:). That, and there were two last things I wanted in for vdb/intel decodings.

Those are all in and v1.0.1 is up on pypi/tagged on github.

**Comment by rakuy0** [comment]
(@Ana06 @williballenthin pinging you guys for awareness as well)

**Comment by mr-tz** [comment]
Thank you very much!
