### ISSUE TITLE
extend funcentries database with additional common prologs

### ISSUE THREAD

**Issue by williballenthin** [vivisect/vivisect#461]
we should extend the list of recognized function prologs so that more code can be brute forced. this issue stems from a key function being missed as reported here:  https://github.com/fireeye/capa/issues/783

a couple resources:
  - the patterns database used by ghidra: https://github.com/NationalSecurityAgency/ghidra/tree/79d8f164f8bb8b15cfb60c5d4faeb8e1c25d15ca/Ghidra/Processors/x86/data/patterns
  - function padding prevalence: https://gist.github.com/stevemk14ebr/d117e8d0fd1432fb2a92354a034ce5b9
  - other resources: https://github.com/williballenthin/lancelot/issues/96

alternatively, perhaps we could add more logic, like: for each pointer to executable data, does it look like code? and/or match a looser set of signatures?

**Comment by atlas0fd00m** [comment]
in theory i like the idea of the intelligence being in here...
on deeper reflection, however, Viv works to never actually use the function prologs for identification, although that's something we can discuss.  instead, ideally Viv identifies functions based on code-flow and function emulation.

we have recently reworked how Viv does ELF PLT analysis, so the plt_popen and plt_recv (etc) should be better identified, even if they are not called from within the code.

Viv's philosophy has always been "better to not identify than to be wrong,"  which is why function prolog identification has been less than desirable for us.  that doesn't mean we can't fix and improve the systems which aren't doing their job.  it just means that the ways in which we improve them may not be the simplest.  ideally we'd like to identify functions by them being referenced as functions and/or called.  if they are referenced (like pushing a function pointer to the stack), we run heuristics to identify what it is most likely.  to test if it's a function, Viv spins up an WorkspaceEmulator and looks for sanity as code (eg.  we find a IF_RET (envi's arch-agnostic flag for "return") instruction, and a few other "function" tests... namely "we don't error out or fail to parse the next instruction"

has this been resolved for you?  
i show that Viv identifies a few of the functions complained to be missing:

![image](https://user-images.githubusercontent.com/9836679/144698556-75538baf-981b-4b05-8624-1bfba2d32099.png)


i don't want this to drop off the radar if it's not satisfactory for your team.

thanks,
@

**Comment by williballenthin** [comment]
yup, understood. recorded it here for awareness, but i get that its not a planned feature for vivisect. i believe we can add such functionality/analysis passes outside of viv, so no problems here.

**Comment by ma77carpenter** [comment]
this is still an open conversation in my opinion.  let's keep talking.  

if, after my comment, you still want prolog-hunting,  what do you think about an analysis module that digs through at the end of autoanalysis (like we do with Pointers), but is an optional analysis module (not enabled by default)?

how would you feel about providing a PR to consider (just for the analysis and prefixes/prologs)?  then we can decide how best to enable/disable it?

**Comment by atlas0fd00m** [comment]
this is still an open conversation in my opinion. let's keep talking.

if, after my comment, you still want prolog-hunting, what do you think about an analysis module that digs through at the end of autoanalysis (like we do with Pointers), but is an optional analysis module (not enabled by default)?

how would you feel about providing a PR to consider (just for the analysis and prefixes/prologs)? then we can decide how best to enable/disable it?

**Comment by williballenthin** [comment]
> what do you think about an analysis module that digs through at the end of autoanalysis (like we do with Pointers), but is an optional analysis module (not enabled by default)?

yeah, this is probably what I'm talking about. such an analysis pass can live either within or external to vivisect, [like we do with FLIRT](https://github.com/williballenthin/viv-utils/blob/master/viv_utils/flirt.py).

> how would you feel about providing a PR to consider 

absolutely. im happy to provide an implementation once i've figured out what we want. i wouldn't expect to lay that effort on you. though, i dont have a timeframe on this - probably just when i feel like we want it again.
