### ISSUE TITLE
missing QTpackages after pip install vivisect

### ISSUE THREAD

**Issue by TomSomerville** [vivisect/vivisect#534]
After installing vivisect through pip on windows 11, vivisec it unable to run due to missing dependencies. PyQT5 and PyQtWebEngine

I had to execute the following in order to get vivisec to run:
pip install PyQt5
pip install PyQtWebEngine

Appears to execute OK afterwards

**Comment by rakuy0** [comment]
When you pip installed vivisect? Was it literally `pip install vivisect`, or was it `pip install vivisect[gui]`?

And how did you run vivisect? Was it with the `-B` option via `python -m vivisect.vivbin -B <mybinary>`? Or was it just `python -m vivisect.vivbin <mybinary>`?

Because we do break out the dependencies for running in a headless analysis mode vs a GUI mode,  so if you're only running in headless mode, vivisect will really only work with the `-B` option because we don't by default install the Qt5 libraries to run the GUI.

**Comment by TomSomerville** [comment]
I literally did `pip install vivisect`
followed by `vivbin fd` where fd is the elf binary I was looking at.

after performing `pip install PyQt5` and `pip install PyQtWebEngine` I was able to execute `vivbin fd`

**Comment by rakuy0** [comment]
Ah. I see the problem. There was a request a while back that on default pip install we only install the headless portions. If you follow this: https://github.com/vivisect/vivisect#installing and this: https://vivisect.readthedocs.io/en/latest/vivisect/quickstart.html#installing it should walk you through the steps to install all in one. 

But just default `pip install vivisect` will only give you the headless version. If you want the gui as well, you want `pip install "vivisect[gui]"`
