### ISSUE TITLE
x86 Linux dissasembly broken

### ISSUE THREAD

**Issue by LesChats** [vivisect/vivisect#551]
Very simple asm code:
![image](https://user-images.githubusercontent.com/51509223/201624362-d7414f8f-5fc4-40de-9aa4-b141206997a0.png)
`nasm -f elf32 foo.s -o foo.o && gcc -m32 -O2  foo.o`
what it is expected: (`r2 a.out`)
![image](https://user-images.githubusercontent.com/51509223/201625166-dc701172-c792-475f-9666-5f7e742eef4e.png)
what I get: (`vivbin a.out)`
![image](https://user-images.githubusercontent.com/51509223/201625112-46a63f16-bea4-40eb-964e-d580ab52e1de.png)

**Comment by LesChats** [comment]
This is a simple example, but I get that type of bug on all my x86 samples. Part of op code are not interpreted, mostly after (int 80, ret, and calls)

**Comment by rakuy0** [comment]
Oh. I see the issue. We just do a blanket "this interrupt doesn't have any branches" for any and all `int` instructions on x86 instead of falling through. We don't filter down any OS information, so interpreting `int 0x80` as a syscall specifically on linux-x86 isn't happening. That has ramifications down the line for whether or not we decide if `main` is a function or not after some emulation.

I'll poke at a fix for the `int 0x80` issue and have a PR up sometime this week.  Thanks for bringing this up!
